### PR TITLE
R&R: add buttons, refactor and format review tile

### PR DESCRIPTION
**Pull request by davidguy3237**
- Implemented functionality for clicking the 'Helpful?' button
- Implemented functionality for clicking the 'Report' button
- Refactored rendering to only show 2 reviews initially
- Implemented functionality for click the 'More Reviews' button
- Added and then removed conditional rendering for review summary
- Added conditional rendering for review body if it's too long
- Reformat date display
- Add some basic tests just to check that everything is rendering
- Add basic formatting and refactoring

### CODE REVIEW

**Comment by davidguy3237** [comment]
[Basic Review Tile formatting & styling](https://trello.com/c/iLnmmRjm/82-basic-review-tile-formatting-styling)

**Comment by davidguy3237** [comment]
[Add button in ReviewsList to show more reviews](https://trello.com/c/TxgAOes0/84-add-button-in-reviewslist-to-show-more-reviews)

**Comment by davidguy3237** [comment]
[Add helpfulness button for reviews](https://trello.com/c/XInK1p8y/83-add-helpfulness-button-for-reviews)

**Comment by davidguy3237** [comment]
[Add basic tests to check rendering](https://trello.com/c/awPZa8yL/86-add-basic-tests-to-check-rendering)

**Comment by davidguy3237** [comment]
[Add report button for reviews](https://trello.com/c/sVJyA2W8/85-add-report-button-for-reviews)

**Review by yoko-8 — APPROVED** [review]
Looks good!

**Pull request merged**
